version: "3"
services:
  node:
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/code
    links:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 0.0.0.0:27017:27017
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=rootpassword
